//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapyTestData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public byte[] PostTime { get; set; }
        public Nullable<int> C_NumOfLikes { get; set; }
        public string C_Content { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public string IsDisplay { get; set; }
        public Nullable<System.TimeSpan> DateWritten { get; set; }
    }
}
