//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapyTestData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsId { get; set; }
        public string Title { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Description { get; set; }
        public string PicUrl { get; set; }
        public string OriginalLink { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> NumOfClicks { get; set; }
        public Nullable<int> N_NumOfLikes { get; set; }
    }
}
