//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapyTestData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsTest3
    {
        public int newsID { get; set; }
        public string title { get; set; }
        public string newsdate { get; set; }
        public string newstime { get; set; }
        public string source { get; set; }
        public string origURL { get; set; }
        public string description { get; set; }
        public string category { get; set; }
    }
}
