//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapyTestData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Sources
    {
        public int UserID { get; set; }
        public int SourceID { get; set; }
        public int SubscribeID { get; set; }
        public byte[] SubscribeTime { get; set; }
    }
}
